name: MSBuild

on:
  push:
  pull_request:

env:
  PROJECT_FILE: opencv.vcxproj

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        build_configuration: ["Release", "Debug"]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get OpenCV itself
      run: git submodule update --init

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.build_configuration}} ${{env.PROJECT_FILE}}
